services:

  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "8085:8080"

    environment:
      - "KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092"
